// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmh3leZzInUVQBiBMMAil_jWTScLX2db0',
    appId: '1:1042230074423:web:50e656d65c9ff9ede673b2',
    messagingSenderId: '1042230074423',
    projectId: 'mydeliveryapp68',
    authDomain: 'mydeliveryapp68.firebaseapp.com',
    storageBucket: 'mydeliveryapp68.firebasestorage.app',
    measurementId: 'G-ED8X3Y1T73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPs-VpRFm6-lt7iy0e6RlL87aMtd0u4nU',
    appId: '1:1042230074423:android:1ab62a786c448466e673b2',
    messagingSenderId: '1042230074423',
    projectId: 'mydeliveryapp68',
    storageBucket: 'mydeliveryapp68.firebasestorage.app',
  );
}
